image: docker:stable

stages:
  - deploy
  - maintenance

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

deploy-supporting-branch-develop:
  stage: deploy
  image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    STACK: ${CI_PROJECT_NAME}
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 10
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    CERT_NAME: ${DEV_CERT_NAME}
    DOMAIN_LIST: ${DEV_DOMAIN_LIST}
    EMAIL_LIST: ${DEV_EMAIL_LIST}
  script:
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} CERT_NAME=${CERT_NAME} DOMAIN_LIST=${DOMAIN_LIST}
      EMAIL_LIST=${EMAIL_LIST}
  environment:
    name: dev
  only:
    - branches
  except:
    - master
    - schedules
  when: manual

deploy-stable-branch-develop:
  stage: deploy
  image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    STACK: ${CI_PROJECT_NAME}
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 10
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    CERT_NAME: ${DEV_CERT_NAME}
    DOMAIN_LIST: ${DEV_DOMAIN_LIST}
    EMAIL_LIST: ${DEV_EMAIL_LIST}
  script:
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} CERT_NAME=${CERT_NAME} DOMAIN_LIST=${DOMAIN_LIST}
      EMAIL_LIST=${EMAIL_LIST}
  environment:
    name: dev
  only:
    - master
  except:
    - schedules
  when: manual

deploy-supporting-branch-production:
  stage: deploy
  image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    STACK: ${CI_PROJECT_NAME}
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 10
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
    CERT_NAME: ${PRO_CERT_NAME}
    DOMAIN_LIST: ${PRO_DOMAIN_LIST}
    EMAIL_LIST: ${PRO_EMAIL_LIST}
  script:
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} CERT_NAME=${CERT_NAME} DOMAIN_LIST=${DOMAIN_LIST}
      EMAIL_LIST=${EMAIL_LIST}
  environment:
    name: pro
  only:
    - branches
  except:
    - master
    - schedules
  when: manual

deploy-stable-branch-production:
  stage: deploy
  image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    STACK: ${CI_PROJECT_NAME}
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 10
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
    CERT_NAME: ${PRO_CERT_NAME}
    DOMAIN_LIST: ${PRO_DOMAIN_LIST}
    EMAIL_LIST: ${PRO_EMAIL_LIST}
  script:
    - >
      deploy.sh COMPOSE_FILE=${COMPOSE_FILE} CERT_NAME=${CERT_NAME} DOMAIN_LIST=${DOMAIN_LIST}
      EMAIL_LIST=${EMAIL_LIST}
  environment:
    name: pro
  only:
    - master
  except:
    - schedules
  when: manual

scheduled-renew-develop:
  stage: maintenance
  image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICE: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
  script: relaunch.sh
  only:
    - schedules

scheduled-renew-production:
  stage: maintenance
  image: registry.gitlab.com/redmic-project/docker/docker-deploy:latest
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICE: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}
  script: relaunch.sh
  only:
    - schedules
