include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy
  - maintenance

variables:
  DD_IMAGE_NAME: docker
  DD_IMAGE_TAG: latest
  STACK: gateway

.deploy:
  variables:
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}

.scheduled-renew:
  stage: maintenance
  variables:
    SERVICE: ${STACK}_${CI_PROJECT_NAME}
  script: relaunch.sh
  only:
    - schedules

scheduled-renew-development:
  extends: .scheduled-renew
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}

scheduled-renew-production:
  extends: .scheduled-renew
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
