version: '3.5'

services:
  certificates-manager:
    deploy:
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

volumes:
  config-vol:
    name: ${CERTBOT_CONFIG_VOL_NAME}
