version: '3.5'

volumes:
  config-vol:
    name: ${CERTBOT_CONFIG_VOL_NAME}
    driver: local
    driver_opts:
      type: ${CERTBOT_CONFIG_VOL_TYPE:-nfs4}
      o: addr=${CERTBOT_CONFIG_VOL_ADDR:-127.0.0.1},${CERTBOT_CONFIG_VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${CERTBOT_CONFIG_VOL_DEVICE:-:/certbot-config-vol/}
