version: '3.5'

services:
  certificates-manager:
    image: docker:dind
    command: manage-certificates
    environment:
      - CERT_NAME
      - DOMAIN_LIST
      - EMAIL_LIST
      - SERVER_STACK
      - SERVER_SERVICE
    networks:
      - redmic-net
    volumes:
      - work-vol:/work
      - acme-vol:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: manage-certificates
        target: /usr/local/bin/manage-certificates
        mode: 0550
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          memory: 52M

networks:
  redmic-net:
    external: true

volumes:
  work-vol:
    name: certificates-manager-vol

  acme-vol:
    name: acme-vol

configs:
  manage-certificates:
    file: ./scripts/manage-certificates.sh
