version: '3.5'

volumes:
  dhparams-vol:
    name: ${DHPARAMS_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: ${DHPARAMS_VOL_DEVICE:-:/dhparams-vol/}

  config-vol:
    name: ${CERTBOT_CONFIG_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: ${CERTBOT_CONFIG_VOL_DEVICE:-:/certbot-config-vol/}

  acme-vol:
    name: ${ACME_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTIONS}
      device: ${ACME_VOL_DEVICE:-:/acme-vol/}
